import {
  Briefcase, Laptop, Building2, TrendingUp, Home, PieChart, Gift, Zap,
  Landmark, UserRound, Undo2, DollarSign, ShoppingCart, UtensilsCrossed,
  Coffee, Package, Wine, Wrench, ShieldCheck, Sofa, Car, Fuel, Bus,
  HeartPulse, Pill, Dumbbell, Brain, Smile, GraduationCap, BookOpen,
  Monitor, Clapperboard, Tv, Gamepad2, Palette, Ticket, ShoppingBag,
  Shirt, Smartphone, Sparkles, Plane, PlaneTakeoff, BedDouble,
  Map as MapIcon, Code, Megaphone, PenTool, Scale, HandCoins, CreditCard,
  FileText, PiggyBank, Heart, Baby, PawPrint, Users,
  type LucideIcon,
} from "lucide-react";

export const getCategoryIcon = (category: string): { icon: LucideIcon; bg: string } => {
  const icons: Record<string, { icon: LucideIcon; bg: string }> = {
    "Salary / Income":        { icon: Briefcase,      bg: "#DCFCE7" },
    "Freelance Income":       { icon: Laptop,         bg: "#DBEAFE" },
    "Business Income":        { icon: Building2,      bg: "#D1FAE5" },
    "Investment Returns":     { icon: TrendingUp,     bg: "#DCFCE7" },
    "Rental Income":          { icon: Home,           bg: "#FEF9C3" },
    "Dividends":              { icon: PieChart,       bg: "#DCFCE7" },
    "Bonus / Incentive":      { icon: Gift,           bg: "#FEE2E2" },
    "Side Hustle":            { icon: Zap,            bg: "#EDE9FE" },
    "Government Benefit":     { icon: Landmark,       bg: "#DBEAFE" },
    "Pension":                { icon: UserRound,      bg: "#FEF3C7" },
    "Gift Received":          { icon: Gift,           bg: "#FCE7F3" },
    "Refund / Cashback":      { icon: Undo2,          bg: "#DCFCE7" },
    "Other Income":           { icon: DollarSign,     bg: "#F3E8FF" },
    "Food & Grocery":         { icon: ShoppingCart,   bg: "#FEF3C7" },
    "Dining Out":             { icon: UtensilsCrossed,bg: "#EEF0FD" },
    "Coffee & Snacks":        { icon: Coffee,         bg: "#FEF3C7" },
    "Takeaway / Delivery":    { icon: Package,        bg: "#FEE2E2" },
    "Alcohol & Bar":          { icon: Wine,           bg: "#FEF9C3" },
    "Rent / Mortgage":        { icon: Home,           bg: "#DBEAFE" },
    "Utilities":              { icon: Zap,            bg: "#FEE2E2" },
    "Internet & Phone":       { icon: Smartphone,     bg: "#EDE9FE" },
    "Home Maintenance":       { icon: Wrench,         bg: "#FEF3C7" },
    "Home Insurance":         { icon: ShieldCheck,    bg: "#DBEAFE" },
    "Furniture & Appliances": { icon: Sofa,           bg: "#F3E8FF" },
    "Transport":              { icon: Car,            bg: "#FEF9C3" },
    "Fuel & Parking":         { icon: Fuel,           bg: "#FEE2E2" },
    "Public Transport":       { icon: Bus,            bg: "#DBEAFE" },
    "Taxi / Ride Share":      { icon: Car,            bg: "#FEF3C7" },
    "Vehicle Maintenance":    { icon: Wrench,         bg: "#F3E8FF" },
    "Vehicle Insurance":      { icon: ShieldCheck,    bg: "#DBEAFE" },
    "Health & Medical":       { icon: HeartPulse,     bg: "#E0E7FF" },
    "Pharmacy":               { icon: Pill,           bg: "#FEE2E2" },
    "Gym & Fitness":          { icon: Dumbbell,       bg: "#DCFCE7" },
    "Mental Health":          { icon: Brain,          bg: "#EDE9FE" },
    "Dental & Vision":        { icon: Smile,          bg: "#DBEAFE" },
    "Health Insurance":       { icon: ShieldCheck,    bg: "#D1FAE5" },
    "Education":              { icon: GraduationCap,  bg: "#DBEAFE" },
    "Tuition & Courses":      { icon: GraduationCap,  bg: "#EDE9FE" },
    "Books & Supplies":       { icon: BookOpen,       bg: "#FEF3C7" },
    "Online Learning":        { icon: Monitor,        bg: "#DBEAFE" },
    "Entertainment":          { icon: Clapperboard,   bg: "#EDE9FE" },
    "Streaming Services":     { icon: Tv,             bg: "#FEE2E2" },
    "Gaming":                 { icon: Gamepad2,       bg: "#EEF0FD" },
    "Hobbies & Leisure":      { icon: Palette,        bg: "#FCE7F3" },
    "Events & Concerts":      { icon: Ticket,         bg: "#FEF3C7" },
    "Shopping":               { icon: ShoppingBag,    bg: "#FCE7F3" },
    "Clothing & Fashion":     { icon: Shirt,          bg: "#EDE9FE" },
    "Electronics & Tech":     { icon: Smartphone,     bg: "#DBEAFE" },
    "Personal Care & Beauty": { icon: Sparkles,       bg: "#FCE7F3" },
    "Gift Given":             { icon: Gift,           bg: "#FEF3C7" },
    "Travel":                 { icon: Plane,          bg: "#DBEAFE" },
    "Flights":                { icon: PlaneTakeoff,   bg: "#EDE9FE" },
    "Hotels & Stay":          { icon: BedDouble,      bg: "#FEF9C3" },
    "Travel Activities":      { icon: MapIcon,        bg: "#DCFCE7" },
    "Business Expense":       { icon: Briefcase,      bg: "#DBEAFE" },
    "Software & Tools":       { icon: Code,           bg: "#EDE9FE" },
    "Marketing & Ads":        { icon: Megaphone,      bg: "#FEE2E2" },
    "Office Supplies":        { icon: PenTool,        bg: "#FEF3C7" },
    "Professional Fees":      { icon: Scale,          bg: "#DBEAFE" },
    "Loan Repayment":         { icon: HandCoins,      bg: "#FEE2E2" },
    "Credit Card Bill":       { icon: CreditCard,     bg: "#FEE2E2" },
    "Bank Fees":              { icon: Landmark,       bg: "#FEF3C7" },
    "Taxes":                  { icon: FileText,       bg: "#FEE2E2" },
    "Savings & Deposit":      { icon: PiggyBank,      bg: "#DCFCE7" },
    "Charity & Donation":     { icon: Heart,          bg: "#FCE7F3" },
    "Childcare":              { icon: Baby,           bg: "#FEF9C3" },
    "Pet Care":               { icon: PawPrint,       bg: "#DCFCE7" },
    "Family Support":         { icon: Users,          bg: "#DBEAFE" },
    "Other":                  { icon: FileText,       bg: "#F3E8FF" },
  };
  return icons[category] ?? { icon: FileText, bg: "#F3E8FF" };
};

export const getCategoryBadge = (category: string): { label: string; bg: string; color: string } => {
  const map: Record<string, { label: string; bg: string; color: string }> = {
    "Salary / Income":        { label: "Salary",      bg: "#DCFCE7", color: "#14532D" },
    "Freelance Income":       { label: "Freelance",   bg: "#DBEAFE", color: "#1E3A8A" },
    "Business Income":        { label: "Business",    bg: "#D1FAE5", color: "#064E3B" },
    "Investment Returns":     { label: "Investment",  bg: "#DCFCE7", color: "#14532D" },
    "Rental Income":          { label: "Rental",      bg: "#FEF9C3", color: "#713F12" },
    "Dividends":              { label: "Dividend",    bg: "#DCFCE7", color: "#14532D" },
    "Bonus / Incentive":      { label: "Bonus",       bg: "#FEE2E2", color: "#7F1D1D" },
    "Side Hustle":            { label: "Side Hustle", bg: "#EDE9FE", color: "#4C1D95" },
    "Government Benefit":     { label: "Govt",        bg: "#DBEAFE", color: "#1E3A8A" },
    "Pension":                { label: "Pension",     bg: "#FEF3C7", color: "#78350F" },
    "Gift Received":          { label: "Gift",        bg: "#FCE7F3", color: "#831843" },
    "Refund / Cashback":      { label: "Refund",      bg: "#DCFCE7", color: "#14532D" },
    "Other Income":           { label: "Income",      bg: "#DCFCE7", color: "#14532D" },
    "Food & Grocery":         { label: "Grocery",     bg: "#FEF3C7", color: "#78350F" },
    "Dining Out":             { label: "Dining",      bg: "#EEF0FD", color: "#3C3489" },
    "Coffee & Snacks":        { label: "Coffee",      bg: "#FEF3C7", color: "#78350F" },
    "Takeaway / Delivery":    { label: "Takeaway",    bg: "#FEE2E2", color: "#7F1D1D" },
    "Alcohol & Bar":          { label: "Alcohol",     bg: "#FEF9C3", color: "#713F12" },
    "Rent / Mortgage":        { label: "Rent",        bg: "#DBEAFE", color: "#1E3A8A" },
    "Utilities":              { label: "Utilities",   bg: "#FEE2E2", color: "#7F1D1D" },
    "Internet & Phone":       { label: "Internet",    bg: "#EDE9FE", color: "#4C1D95" },
    "Home Maintenance":       { label: "Maintenance", bg: "#FEF3C7", color: "#78350F" },
    "Home Insurance":         { label: "Insurance",   bg: "#DBEAFE", color: "#1E3A8A" },
    "Furniture & Appliances": { label: "Furniture",   bg: "#F3E8FF", color: "#4A4568" },
    "Transport":              { label: "Transport",   bg: "#FEF9C3", color: "#713F12" },
    "Fuel & Parking":         { label: "Fuel",        bg: "#FEE2E2", color: "#7F1D1D" },
    "Public Transport":       { label: "Public",      bg: "#DBEAFE", color: "#1E3A8A" },
    "Taxi / Ride Share":      { label: "Taxi",        bg: "#FEF3C7", color: "#78350F" },
    "Vehicle Maintenance":    { label: "Vehicle",     bg: "#F3E8FF", color: "#4A4568" },
    "Vehicle Insurance":      { label: "Insurance",   bg: "#DBEAFE", color: "#1E3A8A" },
    "Health & Medical":       { label: "Medical",     bg: "#FEE2E2", color: "#7F1D1D" },
    "Pharmacy":               { label: "Pharmacy",    bg: "#FEE2E2", color: "#7F1D1D" },
    "Gym & Fitness":          { label: "Gym",         bg: "#DCFCE7", color: "#14532D" },
    "Mental Health":          { label: "Mental",      bg: "#EDE9FE", color: "#4C1D95" },
    "Dental & Vision":        { label: "Dental",      bg: "#DBEAFE", color: "#1E3A8A" },
    "Health Insurance":       { label: "Insurance",   bg: "#D1FAE5", color: "#064E3B" },
    "Education":              { label: "Education",   bg: "#DBEAFE", color: "#1E3A8A" },
    "Tuition & Courses":      { label: "Tuition",     bg: "#EDE9FE", color: "#4C1D95" },
    "Books & Supplies":       { label: "Books",       bg: "#FEF3C7", color: "#78350F" },
    "Online Learning":        { label: "Online",      bg: "#DBEAFE", color: "#1E3A8A" },
    "Entertainment":          { label: "Fun",         bg: "#EDE9FE", color: "#4C1D95" },
    "Streaming Services":     { label: "Streaming",   bg: "#FEE2E2", color: "#7F1D1D" },
    "Gaming":                 { label: "Gaming",      bg: "#EEF0FD", color: "#3C3489" },
    "Hobbies & Leisure":      { label: "Hobbies",     bg: "#FCE7F3", color: "#831843" },
    "Events & Concerts":      { label: "Events",      bg: "#FEF3C7", color: "#78350F" },
    "Shopping":               { label: "Shopping",    bg: "#FCE7F3", color: "#831843" },
    "Clothing & Fashion":     { label: "Clothing",    bg: "#EDE9FE", color: "#4C1D95" },
    "Electronics & Tech":     { label: "Electronics", bg: "#DBEAFE", color: "#1E3A8A" },
    "Personal Care & Beauty": { label: "Beauty",      bg: "#FCE7F3", color: "#831843" },
    "Gift Given":             { label: "Gift",        bg: "#FEF3C7", color: "#78350F" },
    "Travel":                 { label: "Travel",      bg: "#DBEAFE", color: "#1E3A8A" },
    "Flights":                { label: "Flights",     bg: "#EDE9FE", color: "#4C1D95" },
    "Hotels & Stay":          { label: "Hotels",      bg: "#FEF9C3", color: "#713F12" },
    "Travel Activities":      { label: "Activities",  bg: "#DCFCE7", color: "#14532D" },
    "Business Expense":       { label: "Business",    bg: "#DBEAFE", color: "#1E3A8A" },
    "Software & Tools":       { label: "Software",    bg: "#EDE9FE", color: "#4C1D95" },
    "Marketing & Ads":        { label: "Marketing",   bg: "#FEE2E2", color: "#7F1D1D" },
    "Office Supplies":        { label: "Office",      bg: "#FEF3C7", color: "#78350F" },
    "Professional Fees":      { label: "Pro Fees",    bg: "#DBEAFE", color: "#1E3A8A" },
    "Loan Repayment":         { label: "Loan",        bg: "#FEE2E2", color: "#7F1D1D" },
    "Credit Card Bill":       { label: "Credit",      bg: "#FEE2E2", color: "#7F1D1D" },
    "Bank Fees":              { label: "Bank Fee",    bg: "#FEF3C7", color: "#78350F" },
    "Taxes":                  { label: "Tax",         bg: "#FEE2E2", color: "#7F1D1D" },
    "Savings & Deposit":      { label: "Savings",     bg: "#DCFCE7", color: "#14532D" },
    "Charity & Donation":     { label: "Charity",     bg: "#FCE7F3", color: "#831843" },
    "Childcare":              { label: "Childcare",   bg: "#FEF9C3", color: "#713F12" },
    "Pet Care":               { label: "Pet",         bg: "#DCFCE7", color: "#14532D" },
    "Family Support":         { label: "Family",      bg: "#DBEAFE", color: "#1E3A8A" },
    "Other":                  { label: "Other",       bg: "#F3E8FF", color: "#4A4568" },
  };
  return map[category] ?? { label: "Other", bg: "#F3E8FF", color: "#4A4568" };
};